name: server
description: A sample command-line application with basic argument parsing.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.2

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  http: ^1.2.2
  meta: ^1.16.0
  mime: ^2.0.0
  path: ^1.9.1
  uri: ^1.0.0
  xml: ^6.5.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.8
